### ISSUE TITLE
how to train centermask2 on own datasets

### ISSUE THREAD

**Issue by ZHR1997** [youngwanLEE/centermask2#36]
If I want to train on the coco training set I generated, where do I need to modify the code? (Such as category number, category name, etc.)

**Comment by dimabendera** [comment]
I successfully trained a model on my own dataset.

Firstly I create two own datasets in [coco format](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch):
 * for test
    ./centermask2/datasets/numberplate/val/coco_numberplate.json 
    ./centermask2/datasets/numberplate/val/*.jpeg
 * for train
    ./centermask2/datasets/numberplate/train/coco_numberplate.json 
    ./centermask2/datasets/numberplate/train/*.jpeg

Than I create own config files for model with 2 classes <b>BACKGROUND</b> and <b>NUMBERPLATE</b> in dir <b>./centermask2/configs/numberplates</b>

 * <b>numberplate_V_39_eSE_FPN_ms_3x.yaml</b>
```yaml
_BASE_: "Base-NumberPlate-VoVNet.yaml"
MODEL:
  WEIGHTS: "https://www.dropbox.com/s/q98pypf96rhtd8y/vovnet39_ese_detectron2.pth?dl=1"
  VOVNET:
    CONV_BODY : "V-39-eSE"
SOLVER:
  STEPS: (0, 60000)
  MAX_ITER: 60000
OUTPUT_DIR: "output/numberplate/numberplate-V-39-ms-3x"
```

 * <b>Base-NumberPlate-VoVNet.yaml</b>
```yaml
_MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"  
  FCOS:
    POST_NMS_TOPK_TEST: 50
  # PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  MASK_ON: True
  MASKIOU_ON: True
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("numberplate_train",)
  TEST: ("numberplate_val",)
SOLVER:
  CHECKPOINT_PERIOD: 6000
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (0, 60000)
  MAX_ITER: 60000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
```

After that I added to the file <b>./centermask2/train_net.py</b> in the section <b>__main__</b> the registration of my own dataset:
```python3
    # Regist own dataset.
    from detectron2.data.datasets import register_coco_instances
    # train data
    name        = "numberplate_train"
    json_file   = "/var/www/centermask2/datasets/numberplate/train/coco_numberplate.json"
    image_root  = "/var/www/centermask2/datasets/numberplate/train"
    # test data
    name_val        = "numberplate_val"
    json_file_val   = "./centermask2/datasets/numberplate/val/coco_numberplate.json"
    image_root_val  = "./centermask2/datasets/numberplate/val"
    # registr
    register_coco_instances(name, {}, json_file, image_root)
    register_coco_instances(name_val, {}, json_file_val, image_root_val)
```

In the end, I ran the command line:
```bash
DETECTRON2_DATASETS=./centermask2/datasets python3 train_net.py --config-file "configs/numberplates/numberplate_V_39_eSE_FPN_ms_3x.yaml" --num-gpus 1
```
