### ISSUE TITLE
How can I train Centermask on Pascal VOC 2012? (no gt_mask)

### ISSUE THREAD

**Issue by RizhaoCai** [youngwanLEE/centermask2#71]
I would like to try centermask on PascalVOC.
According to line 79-85 of 'datasets/READMD.md'\

## Expected dataset structure for Pascal VOC:
```
VOC20{07,12}/
  Annotations/
  ImageSets/
  JPEGImages/
```

It seems that centermask supports VOC.
However, when I set up the config file as

```yaml
_BASE_: "Base-CenterMask-ResNet-VOC.yaml"
INPUT:
  MASK_FORMAT: "bitmask"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 8
OUTPUT_DIR: "output/CenterMask-R-50-FPN-ms-3x_VOC2012"

DATASETS:
  TEST: ('voc_2012_trainval',)
  TRAIN: ('voc_2012_trainval',)

```
Then I run `train_net.py`

But I find that there is no gt_mask
![image](https://user-images.githubusercontent.com/37952703/98930725-faf88a80-2517-11eb-8e95-ab2b1aec4fba.png)

![image](https://user-images.githubusercontent.com/37952703/98929515-33976480-2516-11eb-9a81-72e59700ff2c.png)

How can I debug to make the centermask on Pascal VOC?

By the way, for PascalVOC2012, there are also instance segmentation labels (bitmasks)
![image](https://user-images.githubusercontent.com/37952703/98930809-1cf20d00-2518-11eb-93e3-f1f4af38b3bd.png)
